---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutumwp
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    ingress.spec.ingressClassName: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: tutumwp.boeing.internal.cloudgenius.app
      http:
        paths:
          - backend:
              service:
                name: tutumwp
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "tutumwp.boeing.internal.cloudgenius.app"
      secretName: tutumwp.boeing.internal.cloudgenius.app
